name: Build and Push

on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in VERSION file
        id: version-check
        run: |
          if [[ -n $(git diff --name-only ${{ github.base_ref }}...${{ github.sha }} | grep '^VERSION$') ]]; then
            echo "::set-output name=version-changed::true"
            echo "true"
          else
            echo "::set-output name=version-changed::false"
            echo "false"
          fi

