name: Build and Test

on:
  push:
    paths:
      - 'VERSION' 

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Docker build and test
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'VERSION'; then
            echo "Docker"
          else
            echo "tests"
          fi
