name: Development Test and Build and Push Docker Image

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/package.sh'
  check_suite:
    types:
      - requested
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 

jobs:
  build-and-push:
    if: ${{ regex(github.event.pull_request.changed_files, '/VERSION/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download latest.zip
        run: echo "test"
  build:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

