name: Build and Test

on:
  push:
    paths-ignore:
      - '**/VERSION'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Check for VERSION file changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'VERSION'; then
            VERSION_CHANGED=true
            echo "True"
          else
            VERSION_CHANGED=false
            echo "False"
          fi

      - name: Docker build and test
        run: |
          if [ "$VERSION_CHANGED" = true ]; then
            echo "docker build"
          else
            echo "Other tests"
          fi
