name: Build and Upload

on:
  push:
    paths:
      - '**'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check for changes in VERSION file
        id: version-check
        run: echo "::set-output name=changed::$(if git diff --name-only ${{ github.base_ref }}...${{ github.sha }} | grep -q 'VERSION'; then echo 'true'; else echo 'false'; fi)"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        if: steps.version-check.outputs.changed == 'true' || contains(github.event.head_commit.modified, 'VERSION') == true
        run: |
          # Build commands here
          echo "BUILD is OK"

      - name: Upload
        if: steps.version-check.outputs.changed == 'true'
        run: |
          # Upload commands here
          echo "UPLOAD is OK"
