name: Development Test and Build and Push Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  check_version_changes:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check_version.outputs.check_version != 'VERSION not changed' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for VERSION changes
        id: check_version
        run: |
          git diff --name-only HEAD^ HEAD | grep VERSION || echo "VERSION not changed"

  build-and-push:
    if: ${{ needs.check_version_changes.outputs.version_changed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download latest.zip
        run: echo "test"

  build:
    needs: check_version_changes
    runs-on: ubuntu-latest
    if: ${{ !needs.check_version_changes.outputs.version_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Add steps for the build process
