name: Development Test and Build and Push Docker Image

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/package.sh'
    types:
      - synchronize
permissions:
  contents: write
  pull-requests: write 

jobs:
  build-and-push:
    #if: ${{ contains(github.event.head_commit.message, 'VERSION') }}
    if: contains(github.event.pull_request.title, 'VERSION')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download latest.zip
        run: echo "test"
  build:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

