name: Build and Push

on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in VERSION file
        id: version-check
        run: |
          echo "VERSION" >> .changed_files
          git diff --name-only ${{ github.base_ref }}...${{ github.sha }} | grep -qv 'VERSION' && echo "OTHER" >> .changed_files || true
          cat .changed_files

  push:
    needs: build
    if: ${{ needs.build.outputs.version-check.run == 'VERSION' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push
        run: |
          # Push commands here
