name: Build and Push

on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in VERSION file
        id: version-check
        run: |
          if git diff --quiet ${{ github.base_ref }}...${{ github.sha }} -- VERSION; then
            echo "::set-output name=version-changed::false"
          else
            echo "::set-output name=version-changed::true"
          fi

