name: Build and Test

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for VERSION file changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'VERSION'; then
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Docker build and test
        run: |
          if [ "${{ env.VERSION_CHANGED }}" = "true" ]; then
            echo "docker build"
          else
            echo "Other tests"
          fi
