# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: 
 [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_URL: antmedia/enterprise
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker pull antmedia/snapshot:latest
          docker tag antmedia/snapshot:latest antmedia/snapshot:latest-main
          docker push antmedia/snapshot:latest-main
