name: Docker 

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
env:
  DEBUG: true

jobs:
  test-docker-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        supervisor: [ false ] 
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download the latest version of Ant Media Server
        run: curl -L -o ant-media-server-community.zip $(curl -s https://api.github.com/repos/ant-media/Ant-Media-Server/releases/latest | grep "browser_download_url" | cut -d '"' -f 4)

      - name: Build with Supervisor=${{ matrix.supervisor }}
        run: |
          docker build \
            --build-arg UseSupervisor=${{ matrix.supervisor }} \
            --build-arg AntMediaServer=ant-media-server-community.zip \
            -t antmedia:${{ matrix.supervisor }} .

      - name: Test Container (Supervisor=${{ matrix.supervisor }})
        run: |
          docker images
          docker run -d -p 5080:5080 --name antmedia-${{ matrix.supervisor }} antmedia:${{ matrix.supervisor }}
          AMS_PID=$(docker exec antmedia-${{ matrix.supervisor }} pgrep -f "antmedia")




          
