name: Docker Build Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-docker-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        supervisor: [true, false]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download the latest version of Ant Media Server
        run: curl -L -o ant-media-server-community.zip $(curl -s https://api.github.com/repos/ant-media/Ant-Media-Server/releases/latest | grep "browser_download_url" | cut -d '"' -f 4)

      - name: Build with Supervisor=${{ matrix.supervisor }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          build-args: |
            UseSupervisor=${{ matrix.supervisor }}
            AntMediaServer=ant-media-server-community.zip
          tags: antmedia:${{ matrix.supervisor }}

      - name: Test Container (Supervisor=${{ matrix.supervisor }})
        run: |
          docker run -d -p 5080:5080 --name antmedia-${{ matrix.supervisor }} antmedia:${{ matrix.supervisor }}
          AMS_PID=$(docker exec antmedia-${{ matrix.supervisor }} pgrep -f "antmedia")
          if [ "${{ matrix.supervisor }}" = "true" ]; then
            # With supervisor: AMS should NOT run with PID 1
            if [ "$AMS_PID" = "1" ]; then
              echo "Error: Ant Media Server is running with PID 1 when supervisor is enabled"
              docker logs antmedia-${{ matrix.supervisor }}
              exit 1
            else
              echo "Success: Ant Media Server is running with PID $AMS_PID (with supervisor)"
            fi
          else
            # Without supervisor: AMS should run with PID 1
            if [ "$AMS_PID" = "1" ]; then
              echo "Success: Ant Media Server is running with PID 1 (without supervisor)"
            else
              echo "Error: Ant Media Server is not running with PID 1 when supervisor is disabled"
              docker logs antmedia-${{ matrix.supervisor }}
              exit 1
            fi
          fi
          
          # Additional validation: Check if supervisor is running when enabled
          if [ "${{ matrix.supervisor }}" = "true" ]; then
            SUPERVISOR_RUNNING=$(docker exec antmedia-${{ matrix.supervisor }} pgrep -f "supervisord" || echo "")
            if [ -z "$SUPERVISOR_RUNNING" ]; then
              echo "Error: Supervisor process not found when it should be enabled"
              exit 1
            fi
          fi


      - name: Check Ant Media Server health with a timeout
        run: |
          timeout=120  
          start_time=$(date +%s)
          until wget http://localhost:5080 -O index.html; do
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))
            
            if [ $elapsed_time -gt $timeout ]; then
              echo "Timeout reached. Ant Media Server did not start within $timeout seconds."
              exit 1
            fi

            echo "Waiting for Ant Media Server to start..."
            sleep 10
          done
          
      - name: Stop and remove the container
        run: docker stop antmediaserver && docker rm antmediaserver
