name: Docker Build Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-docker-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        supervisor: [true, false]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Supervisor=${{ matrix.supervisor }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          build-args: |
            UseSupervisor=${{ matrix.supervisor }}
            LicenseKey=${{ secrets.ANT_MEDIA_LICENSE }}
          tags: antmedia:${{ matrix.supervisor }}

      - name: Test Container (Supervisor=${{ matrix.supervisor }})
        run: |
          # Start container
          docker run -d --name antmedia-${{ matrix.supervisor }} antmedia:${{ matrix.supervisor }}
          
          # Wait for container to start
          sleep 30
          
          # Check if container is running
          CONTAINER_STATUS=$(docker ps -f name=antmedia-${{ matrix.supervisor }} --format '{{.Status}}')
          if [[ $CONTAINER_STATUS != *"Up"* ]]; then
            echo "Container failed to start properly"
            docker logs antmedia-${{ matrix.supervisor }}
            exit 1
          fi
          
          # Get PID of Ant Media Server process
          AMS_PID=$(docker exec antmedia-${{ matrix.supervisor }} pgrep -f "antmedia")
          
          if [ "${{ matrix.supervisor }}" = "true" ]; then
            # With supervisor: AMS should NOT run with PID 1
            if [ "$AMS_PID" = "1" ]; then
              echo "Error: Ant Media Server is running with PID 1 when supervisor is enabled"
              docker logs antmedia-${{ matrix.supervisor }}
              exit 1
            else
              echo "Success: Ant Media Server is running with PID $AMS_PID (with supervisor)"
            fi
          else
            # Without supervisor: AMS should run with PID 1
            if [ "$AMS_PID" = "1" ]; then
              echo "Success: Ant Media Server is running with PID 1 (without supervisor)"
            else
              echo "Error: Ant Media Server is not running with PID 1 when supervisor is disabled"
              docker logs antmedia-${{ matrix.supervisor }}
              exit 1
            fi
          fi
          
          # Additional validation: Check if supervisor is running when enabled
          if [ "${{ matrix.supervisor }}" = "true" ]; then
            SUPERVISOR_RUNNING=$(docker exec antmedia-${{ matrix.supervisor }} pgrep -f "supervisord" || echo "")
            if [ -z "$SUPERVISOR_RUNNING" ]; then
              echo "Error: Supervisor process not found when it should be enabled"
              exit 1
            fi
          fi
          
          # Cleanup
          docker stop antmedia-${{ matrix.supervisor }}
          docker rm antmedia-${{ matrix.supervisor }}
