name: Test MongoDB Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-mongodb:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: | 
          wget https://raw.githubusercontent.com/ant-media/Scripts/3a67539605f0b51042867581c0c81e3365b90a71/install_mongodb.sh 
          ls -alh

      - name: Run MongoDB installation script
        id: install
        run: |
          ./install_mongodb.sh --auto-create | tee /tmp/mongodb-output.log

      - name: Extract MongoDB credentials
        run: |
          USERNAME=$(grep "MongoDB username:" /tmp/mongodb-output.log | awk '{print $3}')
          PASSWORD=$(grep "MongoDB password:" /tmp/mongodb-output.log | awk '{print $3}')
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Verify MongoDB service
        run: |
          systemctl is-active mongod || (echo "MongoDB failed to start" && exit 1)

      - name: Test MongoDB authentication
        run: |
          echo 'show dbs' | mongosh --username "$USERNAME" --password "$PASSWORD" --authenticationDatabase admin || (echo "Authentication failed" && exit 1)
