name: Test MongoDB Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-mongodb:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: wget https://raw.githubusercontent.com/ant-media/Scripts/3a67539605f0b51042867581c0c81e3365b90a71/install_mongodb.sh && chmod +x install_mongodb.sh

      - name: Run MongoDB installation script
        run: sudo ./mongodb-install.sh --auto-create

      - name: Verify MongoDB service
        run: |
          systemctl is-active mongod || (echo "MongoDB failed to start" && exit 1)

      - name: Test MongoDB authentication
        run: |
          echo 'show dbs' | mongosh --username "$(grep 'MongoDB username:' mongodb-install.sh | awk '{print $3}')" --password "$(grep 'MongoDB password:' mongodb-install.sh | awk '{print $3}')" --authenticationDatabase admin || (echo "Authentication failed" && exit 1)
