name: Android SDK CI
on: push

#   Important Information:
#   -It's running in ci.antmedia.cloud and Linux hardware acceleration is enabled.
#    Check this out -> https://developer.android.com/studio/run/emulator-acceleration#vm-linux
#
#   - If runner is not working, start the service.
#     Go to /home/ubuntu/actions-runner and execute the following command
#       sudo ./svc.sh start
#     stop and status commands are also available
#       sudo ./svc.sh status
#       sudo ./svc.sh stop
#     for more information -> https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service#customizing-the-self-hosted-runner-service
#
#   - For reactivecircus/android-emulator-runner@v2.27.0 , ANDROID_SDK_ROOT env should be set
#     in later versions, ANDROID_HOME should be set 
#   
#   - Important: In the actions-runner directory, add the following lines to the .env directory and .bashrc
#     ANDROID_HOME=/home/ubuntu/android
#     ANDROID_SDK_ROOT=/home/ubuntu/android
#     JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/ 
#  


jobs:

  setup-runner:
    runs-on: ubuntu-latest
    outputs:
      server_id: ${{ steps.set-server-id.outputs.server_id }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev libffi-dev libssl-dev
        sudo pip3 install python-openstackclient

