name: upgrade.sh Validation Test
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
  REPO: ${{ github.repository }}

jobs:
  install_and_upgrade_ant_media_server:
    runs-on: ubuntu-latest
    name: Install Previous Version of Ant Media Server
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Debug PR info
        run: |
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
