name: upgrade.sh Validation Test 
#on: [push]
on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
  REPO: ${{ github.repository }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "Target branch is ${{ github.base_ref }}"
