name: Ant Media Server Development Test

on:
  pull_request:
  check_suite:
    types:
      - requested
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    outputs:
      server_id: ${{ steps.set-server-id.outputs.server_id }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
  docker-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      server_id: ${{ steps.set-image-name.outputs.image_name }}
    env:
      DOCKER_URL: antmedia/development
    steps:

      - name: Set Development image name
        id: set-image-name
        run: |
          echo "image_name=${{ env.DOCKER_URL }}" >> $GITHUB_OUTPUT


  clean:
    needs: [setup-runner]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Delete CI Instance
      run: |
        SERVER_ID="${{ needs.docker-build-and-push.outputs.image_name }}"
        echo "server id" $SERVER_ID
